on:
  push:
    branches: [ main ]
    paths:
      - '**/*.js'
      - '**/*.jsx'
      - '**/*.ts'
      - '**/*.tsx'
      - '**/*.mjs'
      - '**/*.json'
      - '**/*.css'
  pull_request:
    branches: [ main ]
    paths:
      - '**.js'
      - '**/*.js'
      - '**/*.jsx'
      - '**/*.ts'
      - '**/*.tsx'
      - '**/*.mjs'
      - '**/*.json'
      - '**/*.css'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - run: wasm-pack test --headless --chrome
      - run: wasm-pack test --headless --firefox
